FloodAutomation/Models/ViewModel/DevicesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FloodAutomation.Models.ViewModel
{
    public class DevicesViewModel
    {
        public Guid Id { get; set; }
        [Required]
        [Display(Name = "Area")]
        public string NameOfPlace { get; set; }
        [Required]
        [Display(Name = "Longitude")]
        public string Longitude { get; set; }
        [Required]
        [Display(Name = "Latitude")]
        public string Latitude { get; set; }
        [Required]
        [StringLength(10, ErrorMessage = "The Phone Number must be at least 10 characters long. Start with 9", MinimumLength = 10)]
        [RegularExpression(@"[9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]+[0-9]", ErrorMessage = "Phone Number is not valid")]
        public string PhoneNumber { get; set; }
        [Required]
        [Display(Name = "Low / Light")]
        public decimal Low { get; set; }
        [Required]
        [Display(Name = "Moderate")]
        public decimal Moderate { get; set; }
        [Required]
        [Display(Name = "High / Heavy")]
        public decimal High { get; set; }
        [Required]
        [Display(Name = "Very High / Intense")]
        public decimal Very_High { get; set; }

        [Required]
        [Display(Name = "Category")]
        public int? CategoryId { get; set; }
        public SelectList Categorys { get; set; }

        public CategoryViewModel Category { get; set; }
    }
}

FloodAutomation/Models/ViewModel/UserViewModel.cs
using FloodAutomation.Core.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FloodAutomation.Models.ViewModel
{
    public class UserViewModel
    {
        public string Id { get; set; }
        [Required]
        [Display(Name = "Role")]
        public string RoleId { get; set; }

        [Display(Name = "Registered")]
        public DateTime DateRegistered { get; set; }
        [Display(Name = "Modified")]
        public DateTime DateModified { get; set; }
        [Required]
        public string Email { get; set; }

        public string UserName { get; set; }
        [Required]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        public string Password { get; set; }
        [Required]

        public string NameIdentifier { get; set; }
        [Required]

        public Gender Gender { get; set; }
        [Required]

        public UserStatuses Status { get; set; }
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [Display(Name = "Temp Password")]
        [MinLength(6)]
        public string TempPassword { get; set; }
        public SelectList Roles { get; set; }
        public string CurrentRole { get; set; }

    

    }

    public class UserDetailsViewModel
    {
        public string Id { get; set; }
        public string NameIdentifier { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public UserStatuses Status { get; set; }
        public string CurrentAction { get; set; }
        public string CurrentRole { get; set; }
    }
}

FloodAutomation/Controllers/AdministrationController.cs
using FloodAutomation.Core.Interfaces.Repository;
using FloodAutomation.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FloodAutomation.Core.Domain;
using FloodAutomation.Hubs;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.Owin;
using FloodAutomation.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System.IO.Ports;
using System.Threading;
using System.Text;
using FloodAutomation.Models.GSM;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using FloodAutomation.Core.Enums;
using System.IO;

namespace FloodAutomation.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdministrationController : BaseController
    {
        private readonly IUnitofWork _context;
        private AutoResetEvent receiveNow;
        private SerialPort port;

        private ApplicationUserManager _userManager;

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public AdministrationController(IUnitofWork context)
        {
            _context = context;
            //_contextUser = new ApplicationDbContext();
            //UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(_contextUser));
            port = null;
            receiveNow = new AutoResetEvent(false);
            //read();

        }


        //public UserManager<ApplicationUser> UserManager { get; set; }
        //public ApplicationDbContext _contextUser { get; set; }
        //public static List<AdminStudentViewModel> userList = new List<AdminStudentViewModel>();
        //public static List<SelectListItem> roleList = new List<SelectListItem>();


        #region Dashboard
        public ActionResult Index()
        {

            return View();
        }
        public ActionResult CounterDevices()
        {
            int CounterDevices = 1;
            var Devices = _context.DevicesRepo.Get(orderBy: a => a.OrderBy(n => n.NameOfPlace), includeProperties: o => o.Category).Select(a => MapperInstance.Map<Devices, DevicesViewModel>(a));
            foreach (var item in Devices)
            {
                ViewBag.CounterDevices = CounterDevices++;
            }
            return PartialView();
        }
        public ActionResult CounterRegUsers()
        {
            int CounterRegUsers = 1;
            var users = _context.UserRepo.Get(orderBy: c => c.OrderBy(o => o.NameIdentifier)).Select(c => MapperInstance.Map<User, UserViewModel>(c)).ToList();
            foreach (var item in users)
            {
                ViewBag.CounterRegUsers = CounterRegUsers++;
            }
            return PartialView();
        }
        public ActionResult UserCounter()
        {
            return PartialView();
        }
        public ActionResult MessageCounter()
        {
            int MessageCounter = 1;
            var notify = _context.MessageNotificationRepo.Get(orderBy: a => a.OrderByDescending(n => n.Id)).Select(a => MapperInstance.Map<MessageNotification, MessageNotificationViewModel>(a));
            foreach (var item in notify)
            {
                ViewBag.MessageCounter = MessageCounter++;

            }
            return PartialView();
        }
        #endregion


        #region TestSMS
        public ActionResult SMS()
        {
            return View();
        }
        public ActionResult GetSMS()
        {
            var SMS = _context.GSMDataRepo.Get(orderBy: a => a.OrderBy(n => n.CNumber)).Select(a => MapperInstance.Map<GSMData, GSMDataViewModel>(a));
            return PartialView("_GetSMS", SMS);
        }
        public ActionResult CreateEdit(Guid? Id)
        {
            var model = new GSMDataViewModel();
            if (Id.HasValue)
            {
                model = MapperInstance.Map<GSMData, GSMDataViewModel>(_context.GSMDataRepo.GetById(Id));
            }
            return PartialView("_CreateEdit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateEdit(GSMDataViewModel model)
        {
            return SaveBasicForm(() =>
            {
                if (model.Id != Guid.Empty)
                {
                    var dev = _context.GSMDataRepo.GetById(model.Id);
                    dev.CNumber = model.CNumber;
                    //dev.DateReceived = model.DateReceived;
                    dev.Message = model.Message;

                    _context.GSMDataRepo.Update(dev);
                    _context.Complete();
                    //  SMSHub.NotifyDataInformationToAllClients();
                }
                else
                {
                    if (model.Id == Guid.Empty)
                    {
                        model.Id = Guid.NewGuid();
                        model.DateReceived = DateTime.Now;
                        var newDev = MapperInstance.Map<GSMData>(model);
                        _context.GSMDataRepo.Add(newDev);
                        _context.Complete();
                        // SMSHub.NotifyDataInformationToAllClients();
                    }
                }
            });
        }
        #endregion


        #region User
        public ActionResult Users()
        {
            return View();
        }
        public async Task<ActionResult> GetUserList()
        {
            var users = _context.UserRepo.Get(orderBy: c => c.OrderBy(o => o.NameIdentifier)).Select(c => MapperInstance.Map<User, UserViewModel>(c)).ToList();

            foreach (var usr in users)
            {
                var userRoles = await UserManager.GetRolesAsync(usr.Id);

                if (userRoles != null)
                {
                    usr.CurrentRole = userRoles.FirstOrDefault();
                }
            }

            return PartialView("_GetUsers", users);

        }


        public async Task<ActionResult> CreateEditUsers(string id = "")
        {
            var model = new UserViewModel();

            if (!string.IsNullOrEmpty(id))
            {
                model = MapperInstance.Map<User, UserViewModel>(_context.UserRepo.GetById(id));

                //get the current role of the user
                var userRoles = await UserManager.GetRolesAsync(id);

                if (userRoles != null)
                {
                    var role = _context.RoleRepo.Get(c => c.Name == userRoles.FirstOrDefault()).FirstOrDefault();

                    if (role != null)
                    {
                        model.RoleId = role.Id;
                    }
                }
            }

            model.Roles = new SelectList(_context.RoleRepo.Get(orderBy: c => c.OrderBy(x => x.Name)), "Id", "Name", model.RoleId);


            return PartialView("_CreateEditUsers", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<ActionResult> CreateEditUsers(UserViewModel model)
        {
            RequestResponseModel response = new RequestResponseModel();
            string userId = "";

            if (!ModelState.IsValid)
            {
                response.Message = GetValidationErrors();
                return ReturnErrorResponse(response);
            }

            try
            {
                if (!string.IsNullOrEmpty(model.Id))
                {
                    userId = model.Id;

                    var userToEdit = _context.UserRepo.GetById(model.Id);

                    //check if email is being changed
                    if (!userToEdit.Email.Equals(model.Email))
                    {
                        if (IsEmailExisting(model.Email))
                        {
                            response.Message = "Email cannot be changed the email is already in used. User's email must be unique.";

                            return ReturnErrorResponse(response);
                        }
                    }
                    userToEdit.NameIdentifier = model.NameIdentifier;
                    userToEdit.Gender = model.Gender;
                    userToEdit.Status = model.Status;
                    userToEdit.Email = model.Email;
                    userToEdit.PhoneNumber = model.PhoneNumber;
                    userToEdit.DateModified = DateTime.Now;


                    _context.UserRepo.Update(userToEdit);
                    _context.Complete();

                    //check if user role is being changed
                    var role = _context.RoleRepo.GetById(model.RoleId);

                    var isUserInRole = await UserManager.IsInRoleAsync(model.Id, role.Name);

                    //user not belong to role then its being changed, we need to update the role
                    if (!isUserInRole)
                    {
                        //remove the previous role of the user

                        var currentRole = await UserManager.GetRolesAsync(model.Id);
                        if (currentRole != null)
                        {
                            await UserManager.RemoveFromRolesAsync(model.Id, currentRole.ToArray());
                        }

                        //add the user to the new role
                        await UserManager.AddToRoleAsync(model.Id, role.Name);
                    }

                    //check if password has changed
                    if (!string.IsNullOrEmpty(model.TempPassword))
                    {
                        //remove and apply the new password
                        await UserManager.RemovePasswordAsync(model.Id);

                        await UserManager.AddPasswordAsync(model.Id, model.TempPassword);
                    }

                }
                else
                {

FloodAutomation/Views/Administration/CounterDevices.cshtml
@ViewBag.CounterDevices

FloodAutomation/Views/Administration/CounterRegUsers.cshtml
@ViewBag.CounterRegUsers

FloodAutomation/Views/Administration/HoursWaterData.cshtml
@{
    ViewBag.Title = "Water Level";
    Layout = "~/Views/Shared/_LayoutAdminLTE.cshtml";
}
@section Menu {
    <script src="~/Scripts/Chart/WaterLevel/WaterLevelChart-menu.js"></script>
}




<div id="box" class="box">
    <div class="box-header with-border">
        <h3 class="box-title"></h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fa fa-times"></i>
            </button>
        </div>
    </div>
    <div class="box-body">
        <div id="container" width='100%' style=" height: 490px; width:auto; margin: 0 auto"></div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/AdminLTE/plugins/jquery-ui/js")
    <script>
        $.widget.bridge('uibutton', $.ui.button);
    </script>


    <script src="~/Scripts/Chart/highstock.js"></script>
    <script src="~/Scripts/Chart/highcharts-more.js"></script>
    <script src="~/Scripts/Chart/exporting.js"></script>
    @*<script src="~/Scripts/Chart/Style2.js"></script>*@
    <script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <script src="~/signalR/hubs"></script>
    <script src="~/Scripts/Chart/WaterLevel/WaterLevelChart.js"></script>

}

FloodAutomation/Views/Administration/PrintRainGaugedDataHistory.cshtml
@model IEnumerable<FloodAutomation.Models.ViewModel.RainGaugeViewModel>

<table class="table table-bordered" id="RainGauged">
    <thead>
        <tr>
            <th>Site Name</th>
            <th>Sender No.</th>
            <th>Data</th>
            <th>Received</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>

        @if (Model != null && Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Devices.NameOfPlace)</td>
                    <td>@Html.DisplayFor(modelItem => item.SenderNumber)</td>
                    <td>@Html.DisplayFor(modelItem => item.Message)</td>
                    <td>@Html.DisplayFor(modelItem => item.DateReceived)</td>
                    <td>@Html.DisplayFor(modelItem => item.Status)</td>

                </tr>

            }
        }
    </tbody>
</table>
<script>
    //$("#WaterLevel").dataTable({
    //    dom: 'lBfrtip',
    //    buttons: [
    //        'print',

    //    ],

    //    "order": [[0, "desc"]],
    //    "iDisplayLength": 100,
    //});
    $(document).on('click', '.btn-printMessage', function (e) {
        e.preventDefault();
        $('.buttons-print').click();
    })

    $('.buttons-print').each(function () {
        $(this).removeClass('btn-default').addClass('hidden');
    })
</script>

FloodAutomation/Views/Administration/RainGauge.cshtml
@{
    ViewBag.Title = "Rain Gauge";
    Layout = "~/Views/Shared/_LayoutAdminLTE.cshtml";
}
@section Menu {
    @Scripts.Render("~/Scripts/FloodMonitoring/RainGauge/RainGaugeJS-menu.js")
}
<div class="box box-default color-palette-box">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="btn btn-default btn-printMessage btn-sm" href="#"><i class="fa fa-print  text-green  refresh-click"></i> <span>Print</span></a>
                </div>
                <div class="panel-body">
                    <div class="data-container">
                        <i class="fa fa-spinner fa-pulse fa-1x fa-fw"></i>  Loading data...
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_GenericModal")


@section styles{
    <link href="~/Scripts/datatable/plugins/datatables.css" rel="stylesheet" />
}
@section Scripts{
    <script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <script src="../signalR/hubs"></script>
    <script src="~/Scripts/FloodMonitoring/RainGauge/RainGauge.js"></script>
    <script src="~/Scripts/datatable/plugins/datatables.js"></script>
    <script src="~/Scripts/datatable/plugins/dataTables.buttons.min.js"></script>
    <script src="~/Scripts/datatable/plugins/buttons.print.min.js"></script>
}

FloodAutomation/Views/Administration/SMS.cshtml
@model IEnumerable<FloodAutomation.Models.AdminStudentViewModel>
@{
    ViewBag.Title = "Index";
    //Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    Layout = "~/Views/Shared/_LayoutAdminLTE.cshtml";

}
@section Menu {
    @Scripts.Render("~/Scripts/SMS/SMSjs-menu.js")
}
<div class="box box-default color-palette-box">

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="#" class="btn btn-primary btn-xs create-sms">Create New</a>
                </div>
                <div class="panel-body">
                    <div class="data-container">
                        <i class="fa fa-spinner fa-pulse fa-1x fa-fw"></i>  Loading data...
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_GenericModal")


@section styles{
    <link href="~/Scripts/datatable/plugins/datatables.css" rel="stylesheet" />
}
@section Scripts{
    <script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <script src="~/Scripts/SMS/SMS.js"></script>
    <script src="~/Scripts/datatable/plugins/datatables.js"></script>
}

FloodAutomation/Views/Administration/UserLog.cshtml
@{
    ViewBag.Title = "User Log";
    Layout = "~/Views/Shared/_LayoutAdminLTE.cshtml";
}
@section Menu {
}
<div class="box box-default color-palette-box">
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="btn btn-default btn-printMessage btn-sm" href="#"><i class="fa fa-print  text-green  refresh-click"></i> <span>Print</span></a>
                </div>
                <div class="panel-body">
                    <div class="data-container">
                        <i class="fa fa-spinner fa-pulse fa-1x fa-fw"></i>  Loading data...
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_GenericModal")


@section styles{
    <link href="~/Scripts/datatable/plugins/datatables.css" rel="stylesheet" />
}
@section Scripts{
    <script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <script src="../signalR/hubs"></script>
    <script src="~/Scripts/Notification/UserNotification.js"></script>
    <script src="~/Scripts/datatable/plugins/datatables.js"></script>
    <script src="~/Scripts/datatable/plugins/dataTables.buttons.min.js"></script>
    <script src="~/Scripts/datatable/plugins/buttons.print.min.js"></script>
}

FloodAutomation/Views/Administration/_CreateEdit.cshtml
@model FloodAutomation.Models.ViewModel.GSMDataViewModel
@using (Html.BeginForm(Html.BeginForm("CreateEdit", "Administration", FormMethod.Post, new { id = "createEdit-sms-form" })))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="response-div"></div>
        <div class="form-group">
            @Html.LabelFor(model => model.CNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

FloodAutomation/Views/Administration/_CreateEditUsers.cshtml
@model FloodAutomation.Models.ViewModel.UserViewModel


<div class="panel-default">
    @using (Html.BeginForm("CreateEditUsers", "Administration", FormMethod.Post, new { id = "user-addedit-form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="response-div"></div>
            <div class="form-group">
                @Html.LabelFor(model => model.NameIdentifier , htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NameIdentifier, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NameIdentifier, "", new { @class = "text-danger" })
                </div>
            </div>

        

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger checkEmailValidationContainer" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TempPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @if (!string.IsNullOrEmpty(Model.Id))
                    {
                        <span style=""><a class="reset-password-btn" href="#">[Reset Password]</a></span>
                        <div class="reset-password-container" @*style="display:none;"*@>
                            @Html.TextBoxFor(model => model.TempPassword, new { @class = "form-control" })
                        </div>
                    }
                    else
                    {
                        @Html.EditorFor(model => model.TempPassword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TempPassword, "", new { @class = "text-danger" })
                    }
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Gender, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Status, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.RoleId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.RoleId, Model.Roles, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
                </div>
            </div>

            
        </div>
    }

</div>
@*<div class="panel-footer">
    <div class="btn-demo">
        <a class="btn-reset-profile-form btn btn-xs btn-default pull-right"><span>Reset</span></a>
        <a class="btn-save-profile-form btn btn-xs btn-primary pull-right"><span>Save Changes</span></a>
    </div>

</div>*@

FloodAutomation/Views/Administration/_GetAllMessagesNotification.cshtml
@model IEnumerable<FloodAutomation.Models.ViewModel.MessageNotificationViewModel>

<style type="text/css">
    .buttons-print {
        /*float: none;
        margin: -36px 0 -70px 168px;*/
    }
</style>

    <table class="table table-bordered" id="MessageNotify">
        <thead>
            <tr>
                <th>Id</th>
                <th>Area</th>
                <th>Category</th>
                <th>Sender Number</th>
                <th>Data</th>
                <th>Status</th>
                <th>Date Received</th>
                <th>History</th>
            </tr>
        </thead>

        <tbody>

            @if (Model != null && Model.Count() > 0)
            {
                foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.Id)</td>
                        <td>@Html.DisplayFor(modelItem => item.DeviceName)</td>
                        <td>@Html.DisplayFor(modelItem => item.CategoryName)</td>
                        <td>@Html.DisplayFor(modelItem => item.SenderNumber)</td>
                        <td>@Html.DisplayFor(modelItem => item.Message)</td>
                        <td>@Html.DisplayFor(modelItem => item.StatusLevel)</td>
                        <td>@Html.DisplayFor(modelItem => item.ConNotifyId)</td>
                        <td><time class="timeago" datetime="@Convert.ToDateTime(item.ConNotifyId)"></time></td>

                    </tr>

                }
            }
        </tbody>
    </table>


<script>
    $(document).ready(function () {
        jQuery("time.timeago").timeago();
    })

    $("#MessageNotify").dataTable({
        dom: 'lBfrtip',
        buttons: [
            'print',

        ],
      
        "order": [[0, "desc"]],
        "iDisplayLength": 100,
    });

    $(document).on('click', '.btn-printMessage', function (e) {
        e.preventDefault();
        $('.buttons-print').click();
    })

    $('.buttons-print').each(function () {
        $(this).removeClass('btn-default').addClass('hidden');
    })

</script>

FloodAutomation/Views/Administration/_GetRainGauge.cshtml
@model IEnumerable<FloodAutomation.Models.ViewModel.RainGaugeViewModel>

<table class="table table-bordered" id="Rain">
    <thead>
        <tr>
            <th>Site Name</th>
            <th>Sender No.</th>
            <th>Data</th>
            <th>Received</th>
            <th>Status</th>
            <th>Index</th>
        </tr>
    </thead>

    <tbody>

        @if (Model != null && Model.Count() > 0)
        {
            foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Devices.NameOfPlace)</td>
                    <td>@Html.DisplayFor(modelItem => item.SenderNumber)</td>
                    <td>@Html.DisplayFor(modelItem => item.Message)</td>
                    <td>@Html.DisplayFor(modelItem => item.DateReceived)</td>
                    <td>@Html.DisplayFor(modelItem => item.Status)</td>
                    <td>@Html.DisplayFor(modelItem => item.Zindex)</td>

                </tr>

            }
        }
    </tbody>
</table>
<script>
    $("#Rain").dataTable({
        dom: 'lBfrtip',
        buttons: [
            'print',

        ],

        "order": [[0, "desc"]],
        "iDisplayLength": 100,
    });
    $(document).on('click', '.btn-printMessage', function (e) {
        e.preventDefault();
        $('.buttons-print').click();
    })

    $('.buttons-print').each(function () {
        $(this).removeClass('btn-default').addClass('hidden');
    })
</script>